---
title: "Forecasting App"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    css: style.css
runtime: shiny
---

```{r global, include=FALSE}
  #libraries------
  library(tidyverse)
  library(here)
  library(fpp3)
  library(scales)
  library(ggrepel)
  library(ggpmisc)
  library(feather)
  library(assertthat)
  #library(devtools)
  #devtools::install_github("rpmartin/aest")
  library(aest)
  #functions----- 
  cagr_percent <- function(df, start_year, end_year){
    assert_that(is.data.frame(df))
    assert_that(end_year > start_year)
    employment_start <- df%>%
      filter(year == start_year)%>%
      pull(employment)
    employment_end <- df%>%
      filter(year == end_year)%>%
      pull(employment)
    cagr <- round(((employment_end/employment_start)^(1/(end_year-start_year))-1)*100, 2)
    tibble(start_year, end_year, cagr)
  } 
  ad_hoc_adjustment <- function(df, vctr){
    add_to_forecast <- c(rep(0, nrow(df)-length(vctr)), vctr)  
    df <- df%>%
      mutate(adjusted_forecast = adjusted_forecast+add_to_forecast)
  }
  #constants----
  bcPalette <- c("#1f4181", "#fabc29")
  historic_start <- 2010
  historic_end <- 2019
  #read in the dataframes----
  assert_that(file.exists(here("data_for_app", "observations.feather")))
  assert_that(file.exists(here("data_for_app", "old_forecast.feather")))
  assert_that(file.exists(here("data_for_app", "driver_data.feather")))
  assert_that(file.exists(here("raw_data", "constraint.csv")))
  obs <- read_feather(here("data_for_app", "observations.feather"))#employment data
  old_forecast <- read_feather(here("data_for_app", "old_forecast.feather"))%>%
    rename(employment = forecast)
  driver_data <- read_feather(here("data_for_app", "driver_data.feather"))
  constraint <- read_csv(here("raw_data", "constraint.csv"), col_types =cols(
  year = col_double(),
  employment = col_double()
))
  #variables----
  end_of_horizon <- year(today()) + 11#the last period to forecast
  forecast_years <- max(obs$year)+1:11 #for the slider inputs
  first_year_of_forecast <- max(obs$year)+1 #forecast cagr and plot annotations relative to this date.
  we_forecast_this_already <- paste0("LMO ", first_year_of_forecast)#for labeling the forecast we have already made.
  last_years_forecast <- paste0("LMO ", first_year_of_forecast-1)#for labeling last years forecast
  series <- unique(obs$industry)#the industries
  industries_with_driver_data <- unique(driver_data$industry) #driver data is available for limited set of industries.
  old_col_names <- c("Start Year", "End Year", paste0(last_years_forecast," CAGR"))
  new_col_names <- c("Start Year", "End Year", paste0(we_forecast_this_already," CAGR"))
  #preliminary calculations----
  industry_share_last_year <- obs%>%
    filter(year == max(year), industry != "ind00-ALL")%>%
    summarize(industry_proportion = 100*employment/sum(employment),
              industry = industry)
  
  if(file.exists(here("forecast_output", "forecasts.csv"))){# if we have made some forecasts this file exists
  current_forecasts <- read_csv(here("forecast_output", "forecasts.csv"), col_types = cols(
  industry = col_character(),
  year = col_double(),
  .model = col_character(),
  raw_forecast = col_double(),
  adjusted_forecast = col_double()))
  current_forecasts <- current_forecasts%>%#reads in the forecasts made thus far...
      group_by(industry, year)%>%
      summarise(adjusted_forecast = last(adjusted_forecast),# and keeps only the last forecast made
                .model=last(.model))
    forecast_already <- unique(current_forecasts$industry)#which industries have we forecast already?
  }else{
    forecast_already <- NULL
  }
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
#the inputs----
selectInput("series", label = "Which industry:",
            choices = series , selected = "ALL")
selectInput("log_transformed", label = "Should data be log transformed?",
            choices = c(TRUE, FALSE), selected = TRUE)
selectInput("show_zero", label = "Should y axis extend to zero?",
            choices = c(TRUE, FALSE), selected = TRUE)
# selectInput("show_arima_old", label = "Show the old auto.arima?",
#             choices = c(TRUE, FALSE), selected = FALSE)
selectInput("train_vs_test", label = "First year of test set",
            choices = (max(obs$year)-5):(max(obs$year)+1) , selected = max(obs$year)-5)
selectInput("chosen", 
            label = "Adjust which model?",
            choices = c("All",
                      "Linear Trend",
                      "Holt's",
                      "Damped Holt's",
                      "Exponential Smoothing",
                      "Arima",
                      "Random Walk with Drift",
                      last_years_forecast,
                      "Driver Data"), 
            selected = "All")

sliderInput("location", "Shift up or down",
                  min = -10000, max = 10000,
                  value = 0, step=50)
sliderInput("slope", "Change slope",
                  min = -5000, max = 5000,
                  value = 0, step=25)

actionButton("save", "Write forecast to disk")

sliderInput("adjust_first", paste("Adjust ", forecast_years[1]),
                  min = -10000, max = 10000,
                  value = 0, step=50)
sliderInput("adjust_second", paste("Adjust ", forecast_years[2]),
                  min = -10000, max = 10000,
                  value = 0, step=50)
sliderInput("adjust_third", paste("Adjust ", forecast_years[3]),
                  min = -10000, max = 10000,
                  value = 0, step=50)
sliderInput("adjust_fourth", paste("Adjust ", forecast_years[4]),
                  min = -10000, max = 10000,
                  value = 0, step=50)
sliderInput("adjust_fifth", paste("Adjust ", forecast_years[5]),
                  min = -10000, max = 10000,
                  value = 0, step=50)
sliderInput("adjust_sixth", paste("Adjust ", forecast_years[6]),
                  min = -10000, max = 10000,
                  value = 0, step=50)
sliderInput("adjust_seventh",paste("Adjust ", forecast_years[7]),
                  min = -10000, max = 10000,
                  value = 0, step=50)
sliderInput("adjust_eighth", paste("Adjust ", forecast_years[8]),
                  min = -10000, max = 10000,
                  value = 0, step=50)
sliderInput("adjust_ninth", paste("Adjust ", forecast_years[9]),
                  min = -10000, max = 10000,
                  value = 0, step=50)
sliderInput("adjust_tenth", paste("Adjust ", forecast_years[10]),
                  min = -10000, max = 10000,
                  value = 0, step=50)
sliderInput("adjust_eleventh", paste("Adjust ", forecast_years[11]),
                  min = -10000, max = 10000,
                  value = 0, step=50)
```

Column
-----------------------------------------------------------------------
###

```{r}
renderPlot({
  #set the forecast horizon----
  horizon <- as.numeric(end_of_horizon)-as.numeric(input$train_vs_test)
  #read in the forecast already made this year (for feedback regarding budget constraint)----
  if(file.exists(here("forecast_output", "forecasts.csv"))){# if we have made some forecasts this file exists
    forecasts <- read_csv(here("forecast_output", "forecasts.csv"))%>%
      group_by(industry, year)%>%
      summarize(adjusted_forecast = last(adjusted_forecast))# only use the latest forecast(if multiple, ignore earlier)
    forecasted_industries <- forecasts%>%
      select(industry)%>%
      distinct()
    `Percent Forecasted`<- inner_join(industry_share_last_year, forecasted_industries, by="industry")%>%
      summarize(sum(industry_proportion))%>%
      pull()
    forecasted_by_year<- forecasts%>%
      filter(year < mean(year))%>% #only for the first 5 years of forecast
      group_by(year)%>%
      summarize(total = sum(adjusted_forecast))%>%
      inner_join(constraint, by="year")%>% #the budget constraint (top line employment)
      mutate(`Industries Forecasted` = nrow(forecasted_industries),
             `Percent Forecasted` = `Percent Forecasted`,
             `Forecasts / Constraint` = round(100*total/employment, 2))%>%
      select(-total, -employment)
  }else{#if we are just starting use an empty tibble
    forecasted_by_year <- tibble(Year = year(today()):(year(today())+4),
                                `Industries Forecasted` = rep(0,5),
                                `Percent Forecasted` = rep(0,5),  
                                `Forecasts / Constraint` = rep(0,5)
                                 )
  }
  #modify last year's forecast to be row bound to new forecasts----
  old_forecast <- old_forecast%>%
      filter(industry == input$series)%>%
    mutate(.model=last_years_forecast,
           .mean=employment,
           year=as.numeric(year),
           model_label = if_else(year == max(year), 
                           as.character(.model), 
                           NA_character_))%>%
    select(industry, .model, year, .mean, model_label)
  #modify driver data to be row bound to new forecasts----
  driver_data <- driver_data%>%
      filter(industry == input$series)%>%
    mutate(.model = "Driver Data",
           .mean = employment,
           year=as.numeric(year),
           model_label = if_else(year == max(year), 
                           as.character(.model), 
                           NA_character_))%>%
    select(industry, .model, year, .mean, model_label)
  #fit the new models----
  filtered_obs <- obs%>%
    filter(industry == input$series)%>%
    mutate(train_vs_test = ifelse(year < input$train_vs_test, "Training", "Testing"),
           train_vs_test=fct_reorder(train_vs_test, year))%>%
    as_tsibble(key = industry, index = year)%>%
    arrange(year)
  if(input$log_transformed == TRUE){
    fit <- filtered_obs %>%
      filter(train_vs_test == "Training")%>%
      model(`Linear Trend` = TSLM(log(employment) ~ trend()),
            `Holt's` = ETS(log(employment) ~ error("A") + trend("A") + season("N")),
            `Damped Holt's` = ETS(log(employment) ~ error("A") + trend("Ad") + season("N")),
            `Exponential Smoothing` = ETS(log(employment)),
            `Arima` = ARIMA(log(employment)),
            `Random Walk with Drift` = RW(log(employment) ~ drift())
            )
  }else{
    fit <- filtered_obs %>%
      filter(train_vs_test == "Training")%>%
      model(`Linear Trend` = TSLM(employment ~ trend()),
            `Holt's` = ETS(employment ~ error("A") + trend("A") + season("N")),
            `Damped Holt's` = ETS(employment ~ error("A") + trend("Ad") + season("N")),
            `Exponential Smoothing` = ETS(employment),
            `Arima` = ARIMA(employment),
            `Random Walk with Drift` = RW(employment ~ drift())
      ) 
  }
  #forecast the new models----
  forecasts <- fit %>%
    forecast(h = paste(horizon, " years"))%>% 
    mutate(year=as.numeric(year),
          model_label = if_else(year == max(year), 
                           as.character(.model), 
                           NA_character_))
  #old auto.arima(possible deletion?)----
  # if(input$show_arima_old == TRUE){
  #   training <- filtered_obs%>%
  #     filter(train_vs_test == "Training")
  #   ts_employment <- ts(training$employment, start = min(training$year))
  #   old_arima <-  forecast::auto.arima(ts_employment,
  #                      # stationary = F, #If this is FALSE then test = adf must be commented out
  #                      stepwise = F,
  #                      trace = T,
  #                      approximation = F,
  #                      # test = "adf",
  #                      allowdrift = T,
  #                      allowmean = T,
  #                      lambda = "auto",
  #                      biasadj = T)
  #   old_arima_forecast <- forecast::forecast(old_arima, h = horizon)%>%
  #     as_tibble(rownames = "year")%>%
  #     mutate(year = as.numeric(year), 
  #            model_label = "auto.arima")
  # }
  #if there is a test set calculate which model has lowest RMSE----
  if(input$train_vs_test < max(filtered_obs$year)){
    rmse <- accuracy(forecasts, filter(filtered_obs, train_vs_test == "Testing"))%>%
      select(.model, RMSE)%>%
      rename(`Unadjusted model` = .model)%>%
      arrange(RMSE)
    best <- rmse%>%
      filter(RMSE == min(RMSE))%>%
      pull(`Unadjusted model`)
  }
  # row bind last year's forecasts and driver data to the new forecasts----
  forecasts <- forecasts%>%
    as_tibble()%>%
    select(-employment)%>%
    rbind(old_forecast)%>%
    rbind(driver_data)
  
  
  
  #create the ad-hoc adjustment vector----
  adjustment_vector <- c(input$adjust_first,
                        input$adjust_second,
                        input$adjust_third,
                        input$adjust_fourth,
                        input$adjust_fifth,
                        input$adjust_sixth,
                        input$adjust_seventh,
                        input$adjust_eighth,
                        input$adjust_ninth,
                        input$adjust_tenth,
                        input$adjust_eleventh
                        )
  # do the slope and overall level adjustment----
  adjusted_forecasts <- forecasts%>%
    mutate(adjusted_forecast = input$location+
                                    input$slope*(as.numeric(year)-
                                    as.numeric(input$train_vs_test))+
                                    .mean,
           raw_forecast = .mean,
           location_adjustment = input$location,
           slope_adjustment = input$slope)%>%
    as_tibble()
  #do the ad-hoc year adjustments----
  adjusted_forecasts <- adjusted_forecasts%>%
    group_by(.model)%>%
    nest()%>%
    mutate(data=map(data,ad_hoc_adjustment, adjustment_vector))%>%
    unnest(data)
  #get the forecast ready to write to disk----
  to_disk <<-  adjusted_forecasts%>%
    filter(.model == input$chosen,
           year >= year(today()))%>%
    select(industry, 
           year, 
           .model, 
           raw_forecast, 
           adjusted_forecast)
  #calculation for old cagr table----
  old_forecast_for_cagr <- old_forecast%>%
    select(year,employment=.mean)
  
  old_cagr <- bind_rows(cagr_percent(filtered_obs, historic_start, historic_end),
                        cagr_percent(old_forecast_for_cagr, first_year_of_forecast-1, first_year_of_forecast+4),
                        cagr_percent(old_forecast_for_cagr, first_year_of_forecast+4, first_year_of_forecast+9),
                        cagr_percent(old_forecast_for_cagr, first_year_of_forecast-1, first_year_of_forecast+9))
  colnames(old_cagr) <- old_col_names
  #calculation for new cagr table----
  new_cagr <- NULL
  if(nrow(to_disk>0)){
   new_forecast_for_cagr <-to_disk%>%
     select(year, employment = adjusted_forecast)
  
  new_cagr <- bind_rows(cagr_percent(filtered_obs, historic_start, historic_end),
                        cagr_percent(new_forecast_for_cagr, first_year_of_forecast, first_year_of_forecast+5),
                        cagr_percent(new_forecast_for_cagr, first_year_of_forecast+5, first_year_of_forecast+10),
                        cagr_percent(new_forecast_for_cagr, first_year_of_forecast, first_year_of_forecast+10))
  colnames(new_cagr) <- new_col_names
  }
  
  #create plot based on filtered_obs(the observed employment levels for the selected industry)----
  p <- ggplot()+
  #  scale_y_continuous(labels = comma)+
    geom_table_npc(mapping = aes(npcx = c(.05, .3, .95),#add the tables
                              npcy = c(.05,.05,.05),
                              label = list(old_cagr, new_cagr, forecasted_by_year)))+
    geom_line(filtered_obs, mapping=aes(year, 
                                       employment, 
                                       colour = train_vs_test),
              lwd = 2, 
              alpha = .5)+
    geom_point(filter(filtered_obs,
                      year == historic_start |
                      year == historic_end | 
                      year == max(filtered_obs$year)), 
               mapping=aes(year, 
                           employment, 
                           colour = train_vs_test), 
               size = 3, 
               alpha = .5)+
    scale_colour_manual(values = bcPalette, guide = "none")+
    labs(title = paste0('Forecasts for ', input$series))+ 
    scale_x_continuous(limits = c(1997, 2034), 
                       breaks = seq(1998, 2032, 2),
                       labels = seq(1998, 2032, 2))+#leave room for labels
    geom_label_repel(data = tail(filtered_obs, 1),#label the last observed employment level
                     mapping = aes(year,
                                 employment,
                                 colour = train_vs_test,
                                 label = label_comma(accuracy = 100)(employment)))+
    geom_label_repel(data = filter(filtered_obs, 
                                  year == historic_start |
                                  year == historic_end), #for historic cagr
                     mapping = aes(year,
                                 employment,
                                 colour = train_vs_test,
                                 label = label_comma(accuracy = 100)(employment)))+
    geom_label_repel(data = head(filtered_obs, 1),#label the training data.
                     mapping = aes(year,
                                 employment,
                                 colour = train_vs_test,
                                 label = "training data"))
  #add last year's forecast----
  p <- p+
    geom_line(data = old_forecast, 
              mapping = aes(year, .mean), lwd=2)
  #either plot all of the forecasts or just the selected----
  if(input$chosen == "All"){
    p <- p+
      geom_line(data = adjusted_forecasts, 
                mapping = aes(year, 
                              adjusted_forecast, 
                              group = .model), 
                colour = "grey50", 
                alpha = .5)+
      geom_label_repel(data = adjusted_forecasts, #label the forecasts with model names
                      mapping = aes(year, 
                                    adjusted_forecast, 
                                    group = .model, 
                                    label = model_label),
                      colour = "grey50",
                      nudge_x = 1,
                      na.rm = TRUE)
  #modify the y axis to include 0 if desired----
    if(input$show_zero == TRUE){#change the y axis limits to include zero
      p <- p+ 
        scale_y_continuous(labels = comma,
                           limits = c(0, 
                                      max(max(filtered_obs$employment), 
                                          max(adjusted_forecasts$adjusted_forecast))))
    }else{
      p <- p+ 
        scale_y_continuous(labels = comma,
                           limits = c(min(min(filtered_obs$employment), 
                                          min(adjusted_forecasts$adjusted_forecast)), 
                                      max(max(filtered_obs$employment), 
                                          max(adjusted_forecasts$adjusted_forecast))))
    }
  #if testing data show best model in bold----
    if(input$train_vs_test < max(filtered_obs$year)){# if there is some testing data bold best model
       p <- p+
         geom_line(data = filter(adjusted_forecasts, .model == best), 
                  mapping = aes(year, adjusted_forecast),
                  lwd = 2,
                  colour = "grey50",
                  alpha = .5)+
        geom_label_repel(data = filtered_obs%>%
                           filter(train_vs_test == "Testing")%>%
                           head(n = 1),#label the testing data.
                     mapping = aes(year,
                                   employment,
                                   colour = train_vs_test,
                                   label = "testing data"))
    }
  }else{#or plot just one forecast
    p <- p+  
      geom_line(data = filter(adjusted_forecasts, .model == input$chosen),
                mapping = aes(year, adjusted_forecast), 
                colour = "grey50", 
                lwd = 2, 
                alpha = .5)+
      geom_point(data = filter(adjusted_forecasts, 
                               .model == input$chosen &
                                year %in% c(first_year_of_forecast, 
                                            first_year_of_forecast+5, 
                                            first_year_of_forecast+10)),
                mapping = aes(year, adjusted_forecast),
                colour = "grey50",
                size = 3, 
                alpha = .5)+
      geom_label_repel(data = filter(adjusted_forecasts, .model == input$chosen),#the model label
                      mapping = aes(year, 
                                    adjusted_forecast, 
                                    label = model_label),
                      colour = "grey50",
                      nudge_x = 2,
                      na.rm = TRUE)+
     geom_label_repel(data = filter(adjusted_forecasts, #some of the forecast employment levels
                                  .model == input$chosen, 
                                  year %in% c(first_year_of_forecast,
                                              first_year_of_forecast+5,
                                              first_year_of_forecast+10)),
                      mapping=aes(year, 
                                  adjusted_forecast, 
                                  label = label_comma(accuracy = 100)(adjusted_forecast)),
                      colour = "grey50")+
    geom_label_repel(data = old_forecast,#the model label
                      mapping = aes(year, 
                                    .mean, 
                                    label = model_label),
                      nudge_x = 2,
                      na.rm = TRUE)+
    geom_point(data = filter(old_forecast, year %in% c(first_year_of_forecast-1,
                                                       first_year_of_forecast+4,
                                                       first_year_of_forecast+9)),
                mapping = aes(year, .mean),
                size = 3)+
      geom_label_repel(data = filter(old_forecast, year %in% c(first_year_of_forecast-1,
                                                               first_year_of_forecast+4, 
                                                               first_year_of_forecast+9)),
                mapping = aes(year,
                              .mean, 
                              label=round(.mean,-2)))
  #modify the y axis to include 0 if desired----
    forecast_max <- adjusted_forecasts%>%
      filter(.model == input$chosen)%>%
      summarize(max(adjusted_forecast))%>%
      pull()
   forecast_min <- adjusted_forecasts%>%
      filter(.model == input$chosen)%>%
      summarize(min(adjusted_forecast))%>%
      pull()
   if(input$show_zero == TRUE){#change the y axis limits to include zero
        p <- p+ 
          scale_y_continuous(labels=comma, 
                             limits = c(0,max(max(filtered_obs$employment),
                                                            forecast_max, 
                                                            max(old_forecast$.mean),
                                                            max(driver_data$.mean)
                                                            )))
      }else{
         p <- p+ 
          scale_y_continuous(labels=comma, 
                             limits = c(min(min(filtered_obs$employment),
                                                            forecast_min, 
                                                            min(old_forecast$.mean),
                                                            min(driver_data$.mean)
                                                            ),
                                        max(max(filtered_obs$employment),
                                                            forecast_max, 
                                                            max(old_forecast$.mean),
                                                            max(driver_data$.mean)
                                                            )))
        
        
        
      } 
  
    }
  #if we have already forecast this industry, show that-----
  if(input$series %in% forecast_already){
    p <- p+
      geom_line(data = filter(current_forecasts, industry == input$series),
                mapping=aes(year,
                            adjusted_forecast), 
                lty=2)+
      geom_label_repel(data = filter(current_forecasts, 
                                     industry==input$series & 
                                      year == min(year)),
                      mapping=aes(year,
                                  adjusted_forecast, 
                                  label=we_forecast_this_already), 
                      nudge_x = -1)
  }
  #if this is an industry with driver data, show that----
  if(input$series %in% industries_with_driver_data){
    p <- p+
      geom_line(data = filter(driver_data, industry == input$series),
                mapping = aes(year, .mean), lty=3)+
      geom_label_repel(data = filter(driver_data, 
                                    industry==input$series &
                                    year == max(year)),
                      mapping=aes(year, 
                                  .mean, 
                                  label="Driver Data"), 
                      nudge_x = 1)
  }
  # old auto.arima code(possible deletion?)----
  # if(input$show_arima_old == TRUE){
  #   p <- p+ #add the original arima model (dashed line)
  #     geom_line(data = old_arima_forecast, mapping = aes(year, `Point Forecast`), lty = 2, alpha = .5)+
  #     geom_label_repel(data = filter(old_arima_forecast, year == min(year)),
  #                      mapping = aes(year, `Point Forecast`, label = model_label), alpha = .5)
  # }
  #pretty up the labels----
  aest_fix_labs(p)
})
#observe the write to disk button----
observeEvent(input$save, {
    write.table(to_disk, 
                here("forecast_output", "forecasts.csv"), 
                append = TRUE, 
                quote = TRUE, 
                sep = ",", 
                row.names = FALSE, 
                col.names =! file.exists(here("forecast_output", "forecasts.csv")))
})
```


